// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kPSM3saJ7ralWfQi8Dnc9hyR1jawW6s',
    appId: '1:291160710799:web:911acd9000f6077a0b1afa',
    messagingSenderId: '291160710799',
    projectId: 'base-app-90b4e',
    authDomain: 'base-app-90b4e.firebaseapp.com',
    storageBucket: 'base-app-90b4e.appspot.com',
    measurementId: 'G-DL4N1FLDQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsnORZVlE7FYNZ5KztdZD9JFVY9NgLmVk',
    appId: '1:291160710799:android:e840a7edc094f1270b1afa',
    messagingSenderId: '291160710799',
    projectId: 'base-app-90b4e',
    storageBucket: 'base-app-90b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42mVnzlSlHi8PLIkiSeZRrQLw8KKMtFw',
    appId: '1:291160710799:ios:7491a04c22743e070b1afa',
    messagingSenderId: '291160710799',
    projectId: 'base-app-90b4e',
    storageBucket: 'base-app-90b4e.appspot.com',
    iosBundleId: 'com.example.baseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42mVnzlSlHi8PLIkiSeZRrQLw8KKMtFw',
    appId: '1:291160710799:ios:7491a04c22743e070b1afa',
    messagingSenderId: '291160710799',
    projectId: 'base-app-90b4e',
    storageBucket: 'base-app-90b4e.appspot.com',
    iosBundleId: 'com.example.baseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5kPSM3saJ7ralWfQi8Dnc9hyR1jawW6s',
    appId: '1:291160710799:web:f321143f93b7200d0b1afa',
    messagingSenderId: '291160710799',
    projectId: 'base-app-90b4e',
    authDomain: 'base-app-90b4e.firebaseapp.com',
    storageBucket: 'base-app-90b4e.appspot.com',
    measurementId: 'G-1BJFNTQQR6',
  );
}
